version : '3.7'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - ${BACKEND_EXPOSE_PORT}:8000
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./backend:/app:delegated
    command: /bin/sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.15
    restart: on-failure
    ports:
      - ${FRONTEND_EXPOSE_PORT}:8000
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./backend/static:/static
      - ./backend/media:/media

