version : '3.7'
services:
  backend:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - ${BACKEND_EXPOSE_PORT}:8000
    env_file: .env
    volumes:
      - ./backend:/app:delegated
    command: /bin/sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresdata:/var/lib/postgres/data:delegated
    ports:
      - ${DB_EXPOSE_PORT}:5432
